#!/usr/bin/env python3
"""
step_25_intrinsic_landscape.py
==============================
Option-(b) test: a V(phi)-driven intrinsic temporal landscape.

step_24 showed that a *matter-sourced* landscape requires beta_A ~ 2900
and produces unscreened lnA contrasts ~3 (ruled out by Hubble-diagram
scatter).  The alternative: the landscape ell(x) = ln A_landscape is
generated by the scalar potential's own dynamics (bounded domains /
patchwork), keeping beta_A = -1 and delta_lnA bounded.  Matter then
surfs a pre-existing terrain under the screened conformal force

    a = g_N - S * c^2 * grad ell        (wells = lnA minima = phi maxima)

and the non-expansion identity requires

    Pi_inferred = -<v . grad ell> = H0 .

This script prescribes a Gaussian random landscape with correlation
length ell_c and rms gradient G_rms, evolves collisionless matter under
Newtonian gravity + screened conformal force, and scans (G_rms, ell_c,
S) for the self-consistent window:

    Pi_inferred ~ H0   AND   v_rms ~ 10^-3 c   AND   sigma_lnA <~ 1e-2 .

The discovered window is the requirement the scalar potential V(phi)
must deliver: bounded excursions delta_lnA ~ G_rms * ell_c, coherence
ell_c, and quasi-static persistence.
"""
import json
import numpy as np
import os

rng = np.random.default_rng(23)

G_SI = 6.674e-11
C_SI = 2.998e8
H0 = 2.27e-18                        # s^-1
RHO_C = 3.0 * H0**2 / (8.0 * np.pi * G_SI)
RHO_M = 0.3 * RHO_C
MPC = 3.086e22
GYR = 3.156e16

N = 64
NP = 64**3
L_MPC = 100.0
L = L_MPC * MPC
DX = L / N
DT = 0.06 * GYR
NSTEPS = 260                          # ~16 Gyr

FOUR_PI_G = 4.0 * np.pi * G_SI
PARTICLE_MASS = RHO_M * L**3 / NP

_k = 2.0 * np.pi * np.fft.fftfreq(N, d=DX)
KX, KY, KZ = np.meshgrid(_k, _k, _k, indexing="ij")
K2 = KX**2 + KY**2 + KZ**2
K2[0, 0, 0] = 1.0


def cic_rho(pos):
    rho = np.zeros((N, N, N))
    g = pos / DX
    i0 = np.floor(g).astype(int) % N
    f = g - np.floor(g)
    for di in (0, 1):
        for dj in (0, 1):
            for dk in (0, 1):
                w = ((1 - di) + (2 * di - 1) * f[:, 0]) * \
                    ((1 - dj) + (2 * dj - 1) * f[:, 1]) * \
                    ((1 - dk) + (2 * dk - 1) * f[:, 2])
                np.add.at(rho, ((i0[:, 0] + di) % N,
                                (i0[:, 1] + dj) % N,
                                (i0[:, 2] + dk) % N), w)
    return rho * PARTICLE_MASS / DX**3


def cic3(field3, pos):
    g = pos / DX
    i0 = np.floor(g).astype(int) % N
    f = g - np.floor(g)
    out = np.zeros((len(pos), 3))
    for di in (0, 1):
        for dj in (0, 1):
            for dk in (0, 1):
                w = ((1 - di) + (2 * di - 1) * f[:, 0]) * \
                    ((1 - dj) + (2 * dj - 1) * f[:, 1]) * \
                    ((1 - dk) + (2 * dk - 1) * f[:, 2])
                ii = ((i0[:, 0] + di) % N, (i0[:, 1] + dj) % N,
                      (i0[:, 2] + dk) % N)
                for c in range(3):
                    out[:, c] += w * field3[c][ii]
    return out


def poisson_phi(rho):
    dk = np.fft.fftn(rho - RHO_M)
    pk = -FOUR_PI_G * dk / K2
    pk[0, 0, 0] = 0.0
    return np.fft.ifftn(pk).real


def grad3(F):
    return np.stack([
        (np.roll(F, -1, 0) - np.roll(F, 1, 0)) / (2 * DX),
        (np.roll(F, -1, 1) - np.roll(F, 1, 1)) / (2 * DX),
        (np.roll(F, -1, 2) - np.roll(F, 1, 2)) / (2 * DX)])


def make_landscape(ell_c_m, g_rms_inv_m):
    """Gaussian random lnA landscape: coherence ell_c, rms gradient
    g_rms (m^-1).  P(k) peaked near k_c = 1/ell_c."""
    d = rng.standard_normal((N, N, N))
    dk = np.fft.fftn(d)
    k = np.sqrt(K2)
    k_c = 1.0 / ell_c_m
    shape = np.exp(-0.5 * ((k - k_c) / (0.5 * k_c)) ** 2) * k**-2
    shape[0, 0, 0] = 0.0
    ek = dk * np.sqrt(shape)
    ek[0, 0, 0] = 0.0
    ell = np.fft.ifftn(ek).real
    g = grad3(ell)
    g_rms_now = np.sqrt(np.mean(np.sum(g**2, 0)))
    ell *= g_rms_inv_m / g_rms_now
    return ell


def run(pos0, vel0, gell, S):
    """Evolve under a = g_N - S c^2 grad ell ; return diagnostics."""
    pos = pos0.copy(); vel = vel0.copy()
    hist = {"t": [], "Pi_inf": [], "vrms": [], "rho_max": []}
    for step in range(NSTEPS):
        rho = cic_rho(pos)
        gvec = -grad3(poisson_phi(rho))
        a = cic3(gvec, pos) - S * C_SI**2 * cic3(gell, pos)
        if step > 0:
            vel += 0.5 * DT * a
        pos = (pos + DT * vel) % L
        rho = cic_rho(pos)
        gvec = -grad3(poisson_phi(rho))
        a = cic3(gvec, pos) - S * C_SI**2 * cic3(gell, pos)
        vel += 0.5 * DT * a
        # Pi_inferred = -<v . grad ell>  (infall toward lnA minima)
        gl = cic3(gell, pos)
        Pi_inf = -np.mean(np.sum(vel * gl, 1))
        hist["t"].append(step * DT / GYR)
        hist["Pi_inf"].append(float(Pi_inf))
        hist["vrms"].append(float(np.sqrt(np.mean(vel**2))))
        hist["rho_max"].append(float(rho.max() / RHO_M))
    return hist


def initial_conditions():
    q = np.indices((64, 64, 64)).reshape(3, -1).T.astype(float)
    q *= L / 64.0
    d = rng.standard_normal((N, N, N))
    dk = np.fft.fftn(d)
    k = np.sqrt(K2)
    k0 = 8.0 * 2 * np.pi / L
    dk *= np.sqrt(1.0 / (1.0 + (k / k0) ** 4))
    dd = np.fft.ifftn(dk).real
    dd /= dd.std(); dd *= 0.8
    Dk = np.fft.fftn(dd) / K2; Dk[0, 0, 0] = 0.0
    D = np.fft.ifftn(Dk).real
    disp = grad3(D)
    disp *= (0.25 * DX) / np.sqrt(np.mean(np.sum(disp**2, 0)))
    pos = (q + cic3(disp, q)) % L
    tau = 1.0 / np.sqrt(FOUR_PI_G * RHO_M)
    vel = cic3(disp, q) / tau
    return pos, vel


def late(hist):
    sl = slice(int(0.6 * NSTEPS), NSTEPS)
    return {
        "Pi_inf_s-1": float(np.mean(hist["Pi_inf"][sl])),
        "Pi_over_H0": float(np.mean(hist["Pi_inf"][sl]) / H0),
        "vrms_over_c": float(np.mean(hist["vrms"][sl]) / C_SI),
        "rho_max_over_mean": float(np.mean(hist["rho_max"][sl])),
    }


def smooth_rho(rho, sigma_cells=1.5):
    """Gaussian-smoothed density field via FFT."""
    k = np.sqrt(K2)
    dk = np.fft.fftn(rho)
    dk *= np.exp(-0.5 * (k * sigma_cells * DX) ** 2)
    return np.fft.ifftn(dk).real


def run_aligned(pos0, vel0, delta_ell, rho_t, w_rho, S):
    """Co-evolving bounded landscape:  ell(x) = -delta_ell *
    tanh((rho_s - rho_t)/w_rho),  recomputed from the smoothed density
    each step.  Wells of bounded depth delta_ell sit on structures;
    gradients live on the isodensity walls that infall streams cross.
    a = g_N - S c^2 grad ell ;  Pi_inf = -<v . grad ell>."""
    pos = pos0.copy(); vel = vel0.copy()
    hist = {"t": [], "Pi_inf": [], "vrms": [], "rho_max": [],
            "gell_rms": []}
    for step in range(NSTEPS):
        rho = cic_rho(pos)
        rs = smooth_rho(rho)
        grs = grad3(rs)
        Fp = np.cosh((rs - rho_t) / w_rho) ** -2 / w_rho   # d[tanh]/d rho
        gell = -delta_ell * Fp[None] * grs                  # grad ell
        gvec = -grad3(poisson_phi(rho))
        a = cic3(gvec, pos) - S * C_SI**2 * cic3(gell, pos)
        if step > 0:
            vel += 0.5 * DT * a
        pos = (pos + DT * vel) % L
        rho = cic_rho(pos)
        rs = smooth_rho(rho)
        grs = grad3(rs)
        Fp = np.cosh((rs - rho_t) / w_rho) ** -2 / w_rho
        gell = -delta_ell * Fp[None] * grs
        gvec = -grad3(poisson_phi(rho))
        a = cic3(gvec, pos) - S * C_SI**2 * cic3(gell, pos)
        vel += 0.5 * DT * a
        gl = cic3(gell, pos)
        Pi_inf = -np.mean(np.sum(vel * gl, 1))
        hist["t"].append(step * DT / GYR)
        hist["Pi_inf"].append(float(Pi_inf))
        hist["vrms"].append(float(np.sqrt(np.mean(vel**2))))
        hist["rho_max"].append(float(rho.max() / RHO_M))
        hist["gell_rms"].append(float(np.sqrt(
            np.mean(np.sum(gell**2, 0))) * MPC))   # in Mpc^-1
    return hist


def main():
    pos0, vel0 = initial_conditions()
    res = {"units": "SI", "box_Mpc": L_MPC, "grid": N, "NP": NP,
           "H0": H0, "identity": "Pi = -<v.grad lnA>; "
           "a = g_N - S c^2 grad ell (beta_A = -1 canonical)"}
    scan = {}
    # gradient amplitude anchored at the identity requirement:
    # |grad lnA| ~ Pi/v ; scan coherence length and screening.
    for ell_c_Mpc, tag in [(0.1, "100kpc"), (0.5, "500kpc"),
                           (2.0, "2Mpc")]:
        ell_c = ell_c_Mpc * MPC
        for g_Mpc in [0.05, 0.2]:
            g_rms = g_Mpc / MPC
            gell = grad3(make_landscape(ell_c, g_rms))
            ell = None
            for S in [1e-5, 1e-4, 1e-3]:
                h = run(pos0, vel0, gell, S)
                s = late(h)
                key = f"lc={tag},g={g_Mpc}/Mpc,S={S:g}"
                scan[key] = s
                scan[key]["delta_lnA_rms"] = float(g_rms * ell_c)
                print(key, json.dumps(s), flush=True)
    res["scan"] = scan
    # ---- Phase B: matter-aligned bounded domain landscape -------------
    aligned = {}
    for delta_ell in [1e-3, 1e-2]:
        for rho_t_f in [1.0, 3.0]:
            rho_t = rho_t_f * RHO_M
            w_rho = 0.5 * rho_t
            for S in [3e-4, 1e-3]:
                h = run_aligned(pos0, vel0, delta_ell, rho_t,
                                w_rho, S)
                s = late(h)
                key = (f"dlA={delta_ell:g},rho_t={rho_t_f}rho,"
                       f"S={S:g}")
                s["delta_lnA"] = delta_ell
                s["gell_rms_Mpc-1"] = float(np.mean(
                    h["gell_rms"][int(0.6 * NSTEPS):]))
                aligned[key] = s
                print("ALIGNED", key, json.dumps(s), flush=True)
    res["aligned_domains"] = aligned
    # find self-consistent windows
    good = []
    for k, v in scan.items():
        ok = (0.3 < v["Pi_over_H0"] < 3.0 and
              3e-4 < v["vrms_over_c"] < 3e-3 and
              v["delta_lnA_rms"] < 1e-2)
        if ok:
            good.append(k)
    for k, v in aligned.items():
        if (0.3 < v["Pi_over_H0"] < 3.0 and
                3e-4 < v["vrms_over_c"] < 3e-3):
            good.append("aligned:" + k)
    res["verdict"] = {
        "self_consistent_windows": good,
        "n_windows": len(good),
        "statement": (
            "intrinsic landscape sustains Pi ~ H0 at physical "
            "velocities with bounded lnA excursions -> V(phi)-driven "
            "channel viable" if good else
            "no window satisfies all constraints in scanned range"),
    }
    outdir = os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))), "results")
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir,
                           "step_25_intrinsic_landscape.json"), "w") as f:
        json.dump(res, f, indent=2)
    print(json.dumps(res["verdict"], indent=1))


if __name__ == "__main__":
    main()
